### ISSUE TITLE
IOS users

### ISSUE THREAD

**Issue by yalgva** [ticgal/gappessentials#1]
Hello,

A very good idea !!! unfortunately all technicians in my Helpdesk are using iphone.

Is it planned to do the same apps for ios ?

Thx for your answer

**Comment by OscarBeiro** [comment]
Hi yalgva,

It is planned an IOS version, but it won't be started without funding. Since IOS development are higher for us. If you are interested, please contact us. https://tic.gal/

In the future, please use this other repository for Gapp related issues. 
https://github.com/ticgal/gapp

This is for Gapp Essentials plugin

Regards,
